// AUTO-GENERATED by scripts/generate-system-provider-ids.ts — DO NOT EDIT.
// Regenerate with `pnpm gen:system-provider-ids`. Source of truth:
// packages/provider-registry/data/providers.json (every provider id except the
// agent/CLI-only backends in CLI_ONLY_PROVIDER_IDS in that script).

import * as z from 'zod'

export const SystemProviderIdSchema = z.enum([
  'anthropic',
  'azure-openai',
  'baichuan',
  'baidu-cloud',
  'dashscope',
  'deepseek',
  'doubao',
  'fireworks',
  'gateway',
  'gemini',
  'github',
  'grok',
  'groq',
  'huggingface',
  'jina',
  'lmstudio',
  'mimo',
  'minimax',
  'minimax-global',
  'mistral',
  'modelscope',
  'moonshot',
  'new-api',
  'nvidia',
  'ollama',
  'openai',
  'opencode',
  'openrouter',
  'ovms',
  'perplexity',
  'qiniu',
  'silicon',
  'stepfun',
  'together',
  'tokenhub',
  'xirang',
  'zai',
  'zhipu'
])

export type SystemProviderId = z.infer<typeof SystemProviderIdSchema>

export const isSystemProviderId = (id: string): id is SystemProviderId => {
  return SystemProviderIdSchema.safeParse(id).success
}

export const SystemProviderIds = {
  anthropic: 'anthropic',
  'azure-openai': 'azure-openai',
  baichuan: 'baichuan',
  'baidu-cloud': 'baidu-cloud',
  dashscope: 'dashscope',
  deepseek: 'deepseek',
  doubao: 'doubao',
  fireworks: 'fireworks',
  gateway: 'gateway',
  gemini: 'gemini',
  github: 'github',
  grok: 'grok',
  groq: 'groq',
  huggingface: 'huggingface',
  jina: 'jina',
  lmstudio: 'lmstudio',
  mimo: 'mimo',
  minimax: 'minimax',
  'minimax-global': 'minimax-global',
  mistral: 'mistral',
  modelscope: 'modelscope',
  moonshot: 'moonshot',
  'new-api': 'new-api',
  nvidia: 'nvidia',
  ollama: 'ollama',
  openai: 'openai',
  opencode: 'opencode',
  openrouter: 'openrouter',
  ovms: 'ovms',
  perplexity: 'perplexity',
  qiniu: 'qiniu',
  silicon: 'silicon',
  stepfun: 'stepfun',
  together: 'together',
  tokenhub: 'tokenhub',
  xirang: 'xirang',
  zai: 'zai',
  zhipu: 'zhipu'
} as const satisfies Record<SystemProviderId, SystemProviderId>

