/**
 * Auto-generated icon catalog for runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Loaded exclusively via dynamic import (icons/loader.ts) — never import statically
 *
 * Generated at: 2026-08-01T00:54:04.518Z
 * Total icons: 75
 */
import { type CompoundIcon } from '../types'
import { Ai21Icon } from './ai21'
import { BaaiIcon } from './baai'
import { ClaudeIcon } from './claude'
import { CogviewIcon } from './cogview'
import { CohereIcon } from './cohere'
import { DeepcogitoIcon } from './deepcogito'
import { DeepseekIcon } from './deepseek'
import { DoubaoIcon } from './doubao'
import { FluxIcon } from './flux'
import { GeminiIcon } from './gemini'
import { GemmaIcon } from './gemma'
import { GlmIcon } from './glm'
import { GlmvIcon } from './glmv'
import { Gpt35TurboIcon } from './gpt-3-5-turbo'
import { Gpt4Icon } from './gpt-4'
import { Gpt41Icon } from './gpt-4-1'
import { Gpt41MiniIcon } from './gpt-4-1-mini'
import { Gpt41NanoIcon } from './gpt-4-1-nano'
import { Gpt4TurboIcon } from './gpt-4-turbo'
import { Gpt4TurboPreviewIcon } from './gpt-4-turbo-preview'
import { Gpt4oIcon } from './gpt-4o'
import { Gpt4oMiniIcon } from './gpt-4o-mini'
import { Gpt5Icon } from './gpt-5'
import { Gpt51Icon } from './gpt-5-1'
import { Gpt51ChatIcon } from './gpt-5-1-chat'
import { Gpt51CodexIcon } from './gpt-5-1-codex'
import { Gpt51CodexMaxIcon } from './gpt-5-1-codex-max'
import { Gpt51CodexMiniIcon } from './gpt-5-1-codex-mini'
import { Gpt52Icon } from './gpt-5-2'
import { Gpt52ChatLatestIcon } from './gpt-5-2-chat-latest'
import { Gpt52CodexIcon } from './gpt-5-2-codex'
import { Gpt52ProIcon } from './gpt-5-2-pro'
import { Gpt53ChatLatestIcon } from './gpt-5-3-chat-latest'
import { Gpt53CodexIcon } from './gpt-5-3-codex'
import { Gpt54Icon } from './gpt-5-4'
import { Gpt54MiniIcon } from './gpt-5-4-mini'
import { Gpt54NanoIcon } from './gpt-5-4-nano'
import { Gpt54ProIcon } from './gpt-5-4-pro'
import { Gpt55Icon } from './gpt-5-5'
import { Gpt55ProIcon } from './gpt-5-5-pro'
import { Gpt56LunaIcon } from './gpt-5-6-luna'
import { Gpt56SolIcon } from './gpt-5-6-sol'
import { Gpt56TerraIcon } from './gpt-5-6-terra'
import { Gpt5CodexIcon } from './gpt-5-codex'
import { Gpt5MiniIcon } from './gpt-5-mini'
import { Gpt5NanoIcon } from './gpt-5-nano'
import { Gpt5ProIcon } from './gpt-5-pro'
import { GptAudioIcon } from './gpt-audio'
import { GptAudioMiniIcon } from './gpt-audio-mini'
import { GptImage1Icon } from './gpt-image-1'
import { GptImage1MiniIcon } from './gpt-image-1-mini'
import { GptImage2Icon } from './gpt-image-2'
import { GptOss120bIcon } from './gpt-oss-120b'
import { GptOss20bIcon } from './gpt-oss-20b'
import { GrokIcon } from './grok'
import { HunyuanIcon } from './hunyuan'
import { InceptionIcon } from './inception'
import { KimiIcon } from './kimi'
import { LingIcon } from './ling'
import { LongcatIcon } from './longcat'
import { MetaIcon } from './meta'
import { MimoIcon } from './mimo'
import { MinimaxIcon } from './minimax'
import { MistralIcon } from './mistral'
import { NousresearchIcon } from './nousresearch'
import { NovaIcon } from './nova'
import { NvidiaIcon } from './nvidia'
import { PalmIcon } from './palm'
import { PerplexityIcon } from './perplexity'
import { QwenIcon } from './qwen'
import { RelaceIcon } from './relace'
import { StepfunIcon } from './stepfun'
import { TrinityIcon } from './trinity'
import { UpstageIcon } from './upstage'
import { WenxinIcon } from './wenxin'
import { type ModelIconKey } from './meta-catalog'

export const MODEL_ICON_CATALOG = {
  ai21: Ai21Icon,
  baai: BaaiIcon,
  claude: ClaudeIcon,
  cogview: CogviewIcon,
  cohere: CohereIcon,
  deepcogito: DeepcogitoIcon,
  deepseek: DeepseekIcon,
  doubao: DoubaoIcon,
  flux: FluxIcon,
  gemini: GeminiIcon,
  gemma: GemmaIcon,
  glm: GlmIcon,
  glmv: GlmvIcon,
  'gpt-3-5-turbo': Gpt35TurboIcon,
  'gpt-4': Gpt4Icon,
  'gpt-4-1': Gpt41Icon,
  'gpt-4-1-mini': Gpt41MiniIcon,
  'gpt-4-1-nano': Gpt41NanoIcon,
  'gpt-4-turbo': Gpt4TurboIcon,
  'gpt-4-turbo-preview': Gpt4TurboPreviewIcon,
  'gpt-4o': Gpt4oIcon,
  'gpt-4o-mini': Gpt4oMiniIcon,
  'gpt-5': Gpt5Icon,
  'gpt-5-1': Gpt51Icon,
  'gpt-5-1-chat': Gpt51ChatIcon,
  'gpt-5-1-codex': Gpt51CodexIcon,
  'gpt-5-1-codex-max': Gpt51CodexMaxIcon,
  'gpt-5-1-codex-mini': Gpt51CodexMiniIcon,
  'gpt-5-2': Gpt52Icon,
  'gpt-5-2-chat-latest': Gpt52ChatLatestIcon,
  'gpt-5-2-codex': Gpt52CodexIcon,
  'gpt-5-2-pro': Gpt52ProIcon,
  'gpt-5-3-chat-latest': Gpt53ChatLatestIcon,
  'gpt-5-3-codex': Gpt53CodexIcon,
  'gpt-5-4': Gpt54Icon,
  'gpt-5-4-mini': Gpt54MiniIcon,
  'gpt-5-4-nano': Gpt54NanoIcon,
  'gpt-5-4-pro': Gpt54ProIcon,
  'gpt-5-5': Gpt55Icon,
  'gpt-5-5-pro': Gpt55ProIcon,
  'gpt-5-6-luna': Gpt56LunaIcon,
  'gpt-5-6-sol': Gpt56SolIcon,
  'gpt-5-6-terra': Gpt56TerraIcon,
  'gpt-5-codex': Gpt5CodexIcon,
  'gpt-5-mini': Gpt5MiniIcon,
  'gpt-5-nano': Gpt5NanoIcon,
  'gpt-5-pro': Gpt5ProIcon,
  'gpt-audio': GptAudioIcon,
  'gpt-audio-mini': GptAudioMiniIcon,
  'gpt-image-1': GptImage1Icon,
  'gpt-image-1-mini': GptImage1MiniIcon,
  'gpt-image-2': GptImage2Icon,
  'gpt-oss-120b': GptOss120bIcon,
  'gpt-oss-20b': GptOss20bIcon,
  grok: GrokIcon,
  hunyuan: HunyuanIcon,
  inception: InceptionIcon,
  kimi: KimiIcon,
  ling: LingIcon,
  longcat: LongcatIcon,
  meta: MetaIcon,
  mimo: MimoIcon,
  minimax: MinimaxIcon,
  mistral: MistralIcon,
  nousresearch: NousresearchIcon,
  nova: NovaIcon,
  nvidia: NvidiaIcon,
  palm: PalmIcon,
  perplexity: PerplexityIcon,
  qwen: QwenIcon,
  relace: RelaceIcon,
  stepfun: StepfunIcon,
  trinity: TrinityIcon,
  upstage: UpstageIcon,
  wenxin: WenxinIcon
} as const satisfies Record<ModelIconKey, CompoundIcon>
