/**
 * Auto-generated icon meta catalog for synchronous runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-08-01T00:54:04.518Z
 * Total icons: 75
 */
import { type IconMeta } from '../types'
import { meta as ai21Meta } from './ai21/meta'
import { meta as baaiMeta } from './baai/meta'
import { meta as claudeMeta } from './claude/meta'
import { meta as cogviewMeta } from './cogview/meta'
import { meta as cohereMeta } from './cohere/meta'
import { meta as deepcogitoMeta } from './deepcogito/meta'
import { meta as deepseekMeta } from './deepseek/meta'
import { meta as doubaoMeta } from './doubao/meta'
import { meta as fluxMeta } from './flux/meta'
import { meta as geminiMeta } from './gemini/meta'
import { meta as gemmaMeta } from './gemma/meta'
import { meta as glmMeta } from './glm/meta'
import { meta as glmvMeta } from './glmv/meta'
import { meta as gpt35TurboMeta } from './gpt-3-5-turbo/meta'
import { meta as gpt4Meta } from './gpt-4/meta'
import { meta as gpt41Meta } from './gpt-4-1/meta'
import { meta as gpt41MiniMeta } from './gpt-4-1-mini/meta'
import { meta as gpt41NanoMeta } from './gpt-4-1-nano/meta'
import { meta as gpt4TurboMeta } from './gpt-4-turbo/meta'
import { meta as gpt4TurboPreviewMeta } from './gpt-4-turbo-preview/meta'
import { meta as gpt4oMeta } from './gpt-4o/meta'
import { meta as gpt4oMiniMeta } from './gpt-4o-mini/meta'
import { meta as gpt5Meta } from './gpt-5/meta'
import { meta as gpt51Meta } from './gpt-5-1/meta'
import { meta as gpt51ChatMeta } from './gpt-5-1-chat/meta'
import { meta as gpt51CodexMeta } from './gpt-5-1-codex/meta'
import { meta as gpt51CodexMaxMeta } from './gpt-5-1-codex-max/meta'
import { meta as gpt51CodexMiniMeta } from './gpt-5-1-codex-mini/meta'
import { meta as gpt52Meta } from './gpt-5-2/meta'
import { meta as gpt52ChatLatestMeta } from './gpt-5-2-chat-latest/meta'
import { meta as gpt52CodexMeta } from './gpt-5-2-codex/meta'
import { meta as gpt52ProMeta } from './gpt-5-2-pro/meta'
import { meta as gpt53ChatLatestMeta } from './gpt-5-3-chat-latest/meta'
import { meta as gpt53CodexMeta } from './gpt-5-3-codex/meta'
import { meta as gpt54Meta } from './gpt-5-4/meta'
import { meta as gpt54MiniMeta } from './gpt-5-4-mini/meta'
import { meta as gpt54NanoMeta } from './gpt-5-4-nano/meta'
import { meta as gpt54ProMeta } from './gpt-5-4-pro/meta'
import { meta as gpt55Meta } from './gpt-5-5/meta'
import { meta as gpt55ProMeta } from './gpt-5-5-pro/meta'
import { meta as gpt56LunaMeta } from './gpt-5-6-luna/meta'
import { meta as gpt56SolMeta } from './gpt-5-6-sol/meta'
import { meta as gpt56TerraMeta } from './gpt-5-6-terra/meta'
import { meta as gpt5CodexMeta } from './gpt-5-codex/meta'
import { meta as gpt5MiniMeta } from './gpt-5-mini/meta'
import { meta as gpt5NanoMeta } from './gpt-5-nano/meta'
import { meta as gpt5ProMeta } from './gpt-5-pro/meta'
import { meta as gptAudioMeta } from './gpt-audio/meta'
import { meta as gptAudioMiniMeta } from './gpt-audio-mini/meta'
import { meta as gptImage1Meta } from './gpt-image-1/meta'
import { meta as gptImage1MiniMeta } from './gpt-image-1-mini/meta'
import { meta as gptImage2Meta } from './gpt-image-2/meta'
import { meta as gptOss120bMeta } from './gpt-oss-120b/meta'
import { meta as gptOss20bMeta } from './gpt-oss-20b/meta'
import { meta as grokMeta } from './grok/meta'
import { meta as hunyuanMeta } from './hunyuan/meta'
import { meta as inceptionMeta } from './inception/meta'
import { meta as kimiMeta } from './kimi/meta'
import { meta as lingMeta } from './ling/meta'
import { meta as longcatMeta } from './longcat/meta'
import { meta as metaMeta } from './meta/meta'
import { meta as mimoMeta } from './mimo/meta'
import { meta as minimaxMeta } from './minimax/meta'
import { meta as mistralMeta } from './mistral/meta'
import { meta as nousresearchMeta } from './nousresearch/meta'
import { meta as novaMeta } from './nova/meta'
import { meta as nvidiaMeta } from './nvidia/meta'
import { meta as palmMeta } from './palm/meta'
import { meta as perplexityMeta } from './perplexity/meta'
import { meta as qwenMeta } from './qwen/meta'
import { meta as relaceMeta } from './relace/meta'
import { meta as stepfunMeta } from './stepfun/meta'
import { meta as trinityMeta } from './trinity/meta'
import { meta as upstageMeta } from './upstage/meta'
import { meta as wenxinMeta } from './wenxin/meta'

export const MODEL_ICON_META_CATALOG = {
  ai21: ai21Meta,
  baai: baaiMeta,
  claude: claudeMeta,
  cogview: cogviewMeta,
  cohere: cohereMeta,
  deepcogito: deepcogitoMeta,
  deepseek: deepseekMeta,
  doubao: doubaoMeta,
  flux: fluxMeta,
  gemini: geminiMeta,
  gemma: gemmaMeta,
  glm: glmMeta,
  glmv: glmvMeta,
  'gpt-3-5-turbo': gpt35TurboMeta,
  'gpt-4': gpt4Meta,
  'gpt-4-1': gpt41Meta,
  'gpt-4-1-mini': gpt41MiniMeta,
  'gpt-4-1-nano': gpt41NanoMeta,
  'gpt-4-turbo': gpt4TurboMeta,
  'gpt-4-turbo-preview': gpt4TurboPreviewMeta,
  'gpt-4o': gpt4oMeta,
  'gpt-4o-mini': gpt4oMiniMeta,
  'gpt-5': gpt5Meta,
  'gpt-5-1': gpt51Meta,
  'gpt-5-1-chat': gpt51ChatMeta,
  'gpt-5-1-codex': gpt51CodexMeta,
  'gpt-5-1-codex-max': gpt51CodexMaxMeta,
  'gpt-5-1-codex-mini': gpt51CodexMiniMeta,
  'gpt-5-2': gpt52Meta,
  'gpt-5-2-chat-latest': gpt52ChatLatestMeta,
  'gpt-5-2-codex': gpt52CodexMeta,
  'gpt-5-2-pro': gpt52ProMeta,
  'gpt-5-3-chat-latest': gpt53ChatLatestMeta,
  'gpt-5-3-codex': gpt53CodexMeta,
  'gpt-5-4': gpt54Meta,
  'gpt-5-4-mini': gpt54MiniMeta,
  'gpt-5-4-nano': gpt54NanoMeta,
  'gpt-5-4-pro': gpt54ProMeta,
  'gpt-5-5': gpt55Meta,
  'gpt-5-5-pro': gpt55ProMeta,
  'gpt-5-6-luna': gpt56LunaMeta,
  'gpt-5-6-sol': gpt56SolMeta,
  'gpt-5-6-terra': gpt56TerraMeta,
  'gpt-5-codex': gpt5CodexMeta,
  'gpt-5-mini': gpt5MiniMeta,
  'gpt-5-nano': gpt5NanoMeta,
  'gpt-5-pro': gpt5ProMeta,
  'gpt-audio': gptAudioMeta,
  'gpt-audio-mini': gptAudioMiniMeta,
  'gpt-image-1': gptImage1Meta,
  'gpt-image-1-mini': gptImage1MiniMeta,
  'gpt-image-2': gptImage2Meta,
  'gpt-oss-120b': gptOss120bMeta,
  'gpt-oss-20b': gptOss20bMeta,
  grok: grokMeta,
  hunyuan: hunyuanMeta,
  inception: inceptionMeta,
  kimi: kimiMeta,
  ling: lingMeta,
  longcat: longcatMeta,
  meta: metaMeta,
  mimo: mimoMeta,
  minimax: minimaxMeta,
  mistral: mistralMeta,
  nousresearch: nousresearchMeta,
  nova: novaMeta,
  nvidia: nvidiaMeta,
  palm: palmMeta,
  perplexity: perplexityMeta,
  qwen: qwenMeta,
  relace: relaceMeta,
  stepfun: stepfunMeta,
  trinity: trinityMeta,
  upstage: upstageMeta,
  wenxin: wenxinMeta
} as const satisfies Record<string, IconMeta>

export type ModelIconKey = keyof typeof MODEL_ICON_META_CATALOG
