/**
 * Auto-generated icon catalog for runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Loaded exclusively via dynamic import (icons/loader.ts) — never import statically
 *
 * Generated at: 2026-08-01T00:54:04.518Z
 * Total icons: 27
 */
import { type CompoundIcon } from '../types'
import { AionlabsIcon } from './aionlabs'
import { AllenaiIcon } from './allenai'
import { AnthropicIcon } from './anthropic'
import { ArceeAiIcon } from './arcee-ai'
import { AzureaiIcon } from './azureai'
import { BailianIcon } from './bailian'
import { CohereIcon } from './cohere'
import { DeepseekIcon } from './deepseek'
import { GoogleIcon } from './google'
import { GrokIcon } from './grok'
import { KlingIcon } from './kling'
import { MinimaxIcon } from './minimax'
import { ModelscopeIcon } from './modelscope'
import { MoonshotIcon } from './moonshot'
import { NewapiIcon } from './newapi'
import { NvidiaIcon } from './nvidia'
import { OllamaIcon } from './ollama'
import { OpenaiIcon } from './openai'
import { OpenrouterIcon } from './openrouter'
import { RecraftIcon } from './recraft'
import { RiverflowIcon } from './riverflow'
import { SiliconIcon } from './silicon'
import { StreamlakeIcon } from './streamlake'
import { TencentCloudTiIcon } from './tencent-cloud-ti'
import { VolcengineIcon } from './volcengine'
import { ZAiIcon } from './z-ai'
import { ZhipuIcon } from './zhipu'
import { type ProviderIconKey } from './meta-catalog'

export const PROVIDER_ICON_CATALOG = {
  aionlabs: AionlabsIcon,
  allenai: AllenaiIcon,
  anthropic: AnthropicIcon,
  'arcee-ai': ArceeAiIcon,
  azureai: AzureaiIcon,
  bailian: BailianIcon,
  cohere: CohereIcon,
  deepseek: DeepseekIcon,
  google: GoogleIcon,
  grok: GrokIcon,
  kling: KlingIcon,
  minimax: MinimaxIcon,
  modelscope: ModelscopeIcon,
  moonshot: MoonshotIcon,
  newapi: NewapiIcon,
  nvidia: NvidiaIcon,
  ollama: OllamaIcon,
  openai: OpenaiIcon,
  openrouter: OpenrouterIcon,
  recraft: RecraftIcon,
  riverflow: RiverflowIcon,
  silicon: SiliconIcon,
  streamlake: StreamlakeIcon,
  'tencent-cloud-ti': TencentCloudTiIcon,
  volcengine: VolcengineIcon,
  'z-ai': ZAiIcon,
  zhipu: ZhipuIcon
} as const satisfies Record<ProviderIconKey, CompoundIcon>
