/**
 * Auto-generated icon meta catalog for synchronous runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-08-01T00:54:04.518Z
 * Total icons: 27
 */
import { type IconMeta } from '../types'
import { meta as aionlabsMeta } from './aionlabs/meta'
import { meta as allenaiMeta } from './allenai/meta'
import { meta as anthropicMeta } from './anthropic/meta'
import { meta as arceeAiMeta } from './arcee-ai/meta'
import { meta as azureaiMeta } from './azureai/meta'
import { meta as bailianMeta } from './bailian/meta'
import { meta as cohereMeta } from './cohere/meta'
import { meta as deepseekMeta } from './deepseek/meta'
import { meta as googleMeta } from './google/meta'
import { meta as grokMeta } from './grok/meta'
import { meta as klingMeta } from './kling/meta'
import { meta as minimaxMeta } from './minimax/meta'
import { meta as modelscopeMeta } from './modelscope/meta'
import { meta as moonshotMeta } from './moonshot/meta'
import { meta as newapiMeta } from './newapi/meta'
import { meta as nvidiaMeta } from './nvidia/meta'
import { meta as ollamaMeta } from './ollama/meta'
import { meta as openaiMeta } from './openai/meta'
import { meta as openrouterMeta } from './openrouter/meta'
import { meta as recraftMeta } from './recraft/meta'
import { meta as riverflowMeta } from './riverflow/meta'
import { meta as siliconMeta } from './silicon/meta'
import { meta as streamlakeMeta } from './streamlake/meta'
import { meta as tencentCloudTiMeta } from './tencent-cloud-ti/meta'
import { meta as volcengineMeta } from './volcengine/meta'
import { meta as zAiMeta } from './z-ai/meta'
import { meta as zhipuMeta } from './zhipu/meta'

export const PROVIDER_ICON_META_CATALOG = {
  aionlabs: aionlabsMeta,
  allenai: allenaiMeta,
  anthropic: anthropicMeta,
  'arcee-ai': arceeAiMeta,
  azureai: azureaiMeta,
  bailian: bailianMeta,
  cohere: cohereMeta,
  deepseek: deepseekMeta,
  google: googleMeta,
  grok: grokMeta,
  kling: klingMeta,
  minimax: minimaxMeta,
  modelscope: modelscopeMeta,
  moonshot: moonshotMeta,
  newapi: newapiMeta,
  nvidia: nvidiaMeta,
  ollama: ollamaMeta,
  openai: openaiMeta,
  openrouter: openrouterMeta,
  recraft: recraftMeta,
  riverflow: riverflowMeta,
  silicon: siliconMeta,
  streamlake: streamlakeMeta,
  'tencent-cloud-ti': tencentCloudTiMeta,
  volcengine: volcengineMeta,
  'z-ai': zAiMeta,
  zhipu: zhipuMeta
} as const satisfies Record<string, IconMeta>

export type ProviderIconKey = keyof typeof PROVIDER_ICON_META_CATALOG
